[platformio]
src_dir = src
include_dir = include
test_dir = test
default_envs = esp32dev

[env:native]
platform = native
test_filter = test_firmware_logic

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_filter = test_embedded_smoke
lib_deps =
  adafruit/Adafruit Fingerprint Sensor Library@2.1.4
  bblanchon/ArduinoJson@6.18.5
