[platformio]
src_dir = src
include_dir = include
test_dir = test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit Fingerprint Sensor Library@2.1.4
  bblanchon/ArduinoJson@6.18.5
